# Generated by Django 4.2 on 2026-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientrecord_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='clinical_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk (0-4)'), ('possible', 'Possible Dengue (5-8)'), ('high', 'High Risk of Dengue (>8)')], max_length=20),
        ),
    ]
