# Generated by Django 4.2 on 2026-05-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_age_user_gender_user_height_user_is_pregnant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
