# Generated by Django 6.0.4 on 2026-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_age_user_gender_user_height_user_is_pregnant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='abdominal_pain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='clinical_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('high', 'High Risk')], max_length=20),
        ),
    ]
