# Generated by Django 4.2 on 2026-07-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
    ]
