# Generated by Django 4.2 on 2026-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_patientrecord_height_remove_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='ns1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
