# Generated by Django 4.2 on 2026-07-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientrecord_add_ns1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expires_at',
        ),
    ]
